name: client_example
version: 0.0.1

environment:
  sdk: ^1.12.0

dependencies:
  logging: ^0.11.2
  event:
    path: ../gen-dart/event
  frugal:
    git:
      url: git@github.com:Workiva/frugal-dart.git
      ref: 1.0.8
  thrift:
    git:
      url: git@github.com:Workiva/thrift-dart.git
      ref: 0.0.4

